name: Dead code analysis

on:
  workflow_dispatch:  # Allows manual triggering
  push:

jobs:
  deadnix:
    name: Deadnix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
      - uses: cachix/cachix-action@v14
        with:
          name: deadnix
      - uses: phucleeuwu/deadnix-action@v1
        with:
          commit_message: "Automated dead code cleanup"
